Feature/older fmriprep
nimh-comppsych/fmriprep-group-report pull request #4
Opened 2022-02-23 00:34 UTC by JessyD

Create fmirprep-group-report for other versions than fmriprep 21.0.0. 
The code was tested using fmriprep  20.0.6 and 20.2.3.

2022-02-23 14:44 UTC, Shotgunosine commented
Can you add a comment like: https://github.com/nimh-comppsych/fmriprep-group-report/blob/dff7d51249af9996f4907e1997e76ecc10d9dddc/fmriprepgr/reports.py#L178-L234 to explain what's going on for pre-21 versions?

2022-02-23 14:46 UTC, Shotgunosine requested changes

2022-02-23 15:54 UTC, JessyD commented on fmriprepgr/reports.py
> +    # Check that the fmriprep version on the html report is the same as the dataset_description.
Ops, thanks for flagging this. It should not be commented out.

2022-03-01 15:06 UTC, Shotgunosine approved these changes

2022-05-25 21:05 UTC, merged